### PR TITLE
[FIX] typos & broken link in README.md

### PR DESCRIPTION
**Pull request by Nabhag8848**
## Changes
- Fix typos and broken link of developer docs in README.md

## About the PR: 
- [x]  I had made same PR previously, but made mistake and push into master branch.

### CODE REVIEW

**Comment by samad-yar-khan** [comment]
Hey @Nabhag8848 thanks for the contribution ! Since this PR is a little old and we recently had some additions to the ReadMe, can you please verify if anything else needs fixing ?

**Comment by Nabhag8848** [comment]
Yep! sure.

**Comment by Nabhag8848** [comment]
`one changes required`:
1) There is nothing like `/github issues` anymore cause that feat has been merged with `/github me` in #32

`one possible changes`: 
1) I see we don't have `/github help` command its just being resolved to command not exist and giving the helper message. `/github` would lead to same result. should we migrate it to `/github` for helper or user are experience more with the `/github help`?

**Comment by Nabhag8848** [comment]
Hey @samad-yar-khan , we will need one further change in Readme, looking for your verification.

- Currently to install dependency we have `npm install` but as we have package-lock.json it should be `npm ci` to have same dependency version for every contributor as in `master branch`.

- Difference between both of them is when we install using `npm ci` it won't make the changes in package-lock.json as it will install the dependencies from **package-lock.json** and won't look at package.json.

While when we install the dependency using npm install it looks at package.json and what difference it make is:

- Lets say we have X dependency version **`^1.12.1`** so here if the dependency has new minor release(s) then package-lock.json will get updated.

As per official docs: https://docs.npmjs.com/cli/v9/commands/npm-ci

Thus, we can avoid encountering the package-lock.json updated versions in contributors PR like PR #49 and every contributor is on same dependency versions.

**Pull request closed without merging**
