### PR TITLE
Gitpodify GitHub app

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Issue(s) 
The environment setup for Rocket.Chat App development is super difficult for any beginner to start with, that serves as a major hinderance for developers. They have to go through so many environment setup steps with millions of compatibility issues. Along with this, it takes a lots of resource to keep Rocket.Chat server alive while app development including tons of other stuff.

## Acceptance Criteria fulfillment

- [x] Add `.gitpod.yaml` file, with thrust initialization.
- [x] Add Workspace image including docker & node, with thrust already installed.
- [x] Update readme with `Open In Gitpod` Button.

## Demo of the Implementation 

https://user-images.githubusercontent.com/72302948/219952734-3c531b85-f6fe-4031-962f-629c8db21145.mp4

### CODE REVIEW

**Comment by henit-chobisa** [comment]
Hey @samad-yar-khan, here it is 🙈
A PR that laid me make a new Product, [Thrust](https://github.com/henit-chobisa/Thrust.RC) 🧑🏼‍🚀

**Comment by Nabhag8848** [comment]
Just Wow @henit-chobisa .This is Cool.Kudos to you!

**Comment by henit-chobisa** [comment]
> Just Wow @henit-chobisa .This is Cool.Kudos to you!

Thanks @Nabhag8848 🙏

**Comment by samad-yar-khan** [comment]
Hey @henit-chobisa  This is an amazing contribution to the Rocket.Chat Apps Eco System. This will make app testing easier than ever  :tada:
I tested the app [Thrust.RC](https://github.com/henit-chobisa/Thrust.RC), there are minor bugs related to rendering  and sending channel messages. Looking forward to future version Thrust fixing these small bugs :100:

**Review by samad-yar-khan — APPROVED** [review]
LGTM :100:

**Pull request merged**
