### PR TITLE
Bug #73: Markdown render while listing all issues of repository

### PR DESCRIPTION
**Pull request by kanishbodhwani**
## Proposed changes (including videos or screenshots)

- Markdown is fixed with all possible issues that can occur due to URL. Eg - Removed Square brackets , backticks and quotes.  

ss

## Further comments

- Removing all the occurrences of **NOT-VALID** URL characters.

### CODE REVIEW

**Comment by kanishbodhwani** [comment]
@samad-yar-khan Please review this

**Comment by Nabhag8848** [comment]
Hey @kanishbodhwani Nice! but i think you mistakenly worked on main branch. Make sure you create new branch and work on that and open PR with branch you created.

**Comment by samad-yar-khan** [comment]
@kanishbodhwani , have we considered all cases for this ?

**Comment by samad-yar-khan** [comment]
@kanishbodhwani , I think we can maybe handle for cases where the Title has backticks "`FIX` Modal"

**Comment by samad-yar-khan** [comment]
@kanishbodhwani  Can this be extended to the method that sends the PR List to the channel ?

**Pull request merged**
