### PR TITLE
[Feature] GitHub Search

### LINKED ISSUE #12: [Feature] GitHub Search integration enabling users to search for Issues and Pull Request
## Why do we need this ?

As a GitHub App developer

**I need to**:  Add a search feature which enables users to query issues and pull requests 

**So That**: users can search for relevant Pull Requests and Issues right from Rocket.Chat and share them in the desired channel, enhancing the communication and collaboration between developers.

## Acceptance Criteria

- [ ] Enable user to trigger a search modal using `/github search`.
- [ ] Enable user to enter search queries and fetch relevant results.
- [ ] User Should be able to view and select the relevant search results in a another search view modal. 
- [ ] Users should be able to send selected search result in the desired room.
- [ ] Add documentation to the wiki for the GitHub search mechanism and user-flow
- [ ] Handle non authenticated users edge cases. (GitHub Search API requires OAuth Token)

## Further Comments / Referances 

- GSoC Proposal mentioned the search result to be fetched directly in chat but viewing them in a modal and sending relevant results to  the channels seems like a better user experience.
- Wireframes for the Search Modal Mentioned in the Google Summer of Code Proposal :  
image

### PR DESCRIPTION
**Pull request by samad-yar-khan**
## Issue(s) 

closes #12  

## Acceptance Criteria fulfillment

- [x] Enable user to trigger a search modal using `/github search`.
- [x] Enable user to enter search queries and fetch relevant results.
- [x] User Should be able to view and select the relevant search results in a another search view modal. 
- [x] Users should be able to send selected search result in the desired room.
- [x] Add documentation to the wiki for the GitHub search mechanism and user-flow
- [x] Handle non authenticated users edge cases. (GitHub Search API requires OAuth Token)

## Proposed changes (including videos or screenshots)

- Added [Documentation](https://github.com/RocketChat/Apps.Github22/wiki/GitHub-Search) for GitHub Search Feature 
- Added GitHub Search Modal which allows users to search repository issues and pull request based on different filters.

https://user-images.githubusercontent.com/70485812/180270074-7a29d6bb-40cf-4f8e-bd5f-2fe7ef0a2052.mp4

- Added Result Sharing functionality. Enabled user to send selected Pull Request or Issue to current room by clicking on `Share`. Users can visit the issue/pull request on GitHub by clicking on `GitHub` button.

https://user-images.githubusercontent.com/70485812/180274575-2d3a1c16-ba7f-454d-bafa-6b29a4b0623f.mp4

- Added `View Changes` button, which will be added to all Pull Request Results. Users can click on `View Changes` and see more details of the PR, including code changes. ( This can be one of the major painkillers. This will be upgraded to a code editor with indentation depending on the [fuselage team PR]() )

https://user-images.githubusercontent.com/70485812/180278267-b0b2e4f5-5d59-4146-b075-e6f63af022d9.mp4

## Further comments

- Some of the features like reviewing code changes of a PR has been integrated with this Pull Request Change Result to improve collaboration.

### CODE REVIEW

**Comment by samad-yar-khan** [comment]
@RonLek Can you please take a look at this PR and suggest any changes.

**Review by RonLek — APPROVED** [review]

**Comment by RonLek** [comment]
Thanks @samad-yar-khan for your PR. Can we also copy the link to clipboard when the user clicks `Share`. Do you think that would be possible with the Apps-Engine?

**Comment by samad-yar-khan** [comment]
> Thanks @samad-yar-khan for your PR. Can we also copy the link to clipboard when the user clicks `Share`. Do you think that would be possible with the Apps-Engine?

@RonLek We can right click on the `GitHub` Button and copy the link, the GitHub button is linked to that URL. I will see if its possible to add a `Copy To Clipboard` type of option,  that would be a good feature ! But that would ultimately depend on the `fuselage` implementation, I will take a look :)

**Comment by Sing-Li** [comment]
Excellent!    (I have been skeptical in the recent past about the value of this feature without the ability to review code in detail)

One urgent suggestion is -- in the case of "Share"  ..... 

1.   allow multiple "Share" from one search  - by toggle-highlighting the SHARE buttons (turning blue/highlighted)  and adding a SEND ALL SHARED  button at the bottom

2.  add a "summary message" free text at the top;  it defaults to a description of the search parameters you applied --- but allows user override and editing

Then when "SEND ALL SHARED" is clicked,  the "summary message" is appended with each of the highlighted issues and inserted as a larger message into the conversation.

This will "match" a typical usage of this feature significantly better and avoid having to do `/github search` multiple times in the workflow.

**Comment by samad-yar-khan** [comment]
@Sing-Li @RonLek I have added the multi-share feature mentioned in the comment. Have a look :) 

https://user-images.githubusercontent.com/70485812/184395134-59288ef2-a5bc-4c66-9116-923bd6ec86a4.mp4



> Excellent! (I have been skeptical in the recent past about the value of this feature without the ability to review code in detail)
> 
> One urgent suggestion is -- in the case of "Share" .....
> 
> 1. allow multiple "Share" from one search  - by toggle-highlighting the SHARE buttons (turning blue/highlighted)  and adding a SEND ALL SHARED  button at the bottom
> 2. add a "summary message" free text at the top;  it defaults to a description of the search parameters you applied --- but allows user override and editing
> 
> Then when "SEND ALL SHARED" is clicked, the "summary message" is appended with each of the highlighted issues and inserted as a larger message into the conversation.
> 
> This will "match" a typical usage of this feature significantly better and avoid having to do `/github search` multiple times in the workflow.

**Review by RonLek — APPROVED** [review]
Great work @samad-yar-khan . LGTM.

**Pull request merged**
