### PR TITLE
Spelling fix

### PR DESCRIPTION
**Pull request by VipinDevelops**
## Acceptance Criteria fulfillment

Fixed the spelling in all the files and comments in the entire codebase 

- replace inavlid to invalid
- replace Subsciption to Subscription
- replace Subsciptions to Subscriptions
-  replace Subsciptions to Subscriptions 
- replace subsciptions to subscriptions
- replace subsciptionsModal with subscriptionsModal
-  replace subsciption to subscription
- replace Reqeust to Request

### CODE REVIEW

**Comment by VipinDevelops** [comment]
Hey @samad-yar-khan Can you please review this PR.

**Comment by samad-yar-khan** [comment]
@VipinDevelops Thanks a lot for the contributions, Can you please resolve the merge conflicts ?

**Comment by VipinDevelops** [comment]
> @VipinDevelops Thanks a lot for the contributions, Can you please resolve the merge conflicts ?

sure I fixed the merge conflicts please have a look.

**Comment by VipinDevelops** [comment]
Hey @samad-yar-khan sir could you please review this PR

**Review by samad-yar-khan — APPROVED** [review]
LGTM @VipinDevelops . Thanks a lot 💯

**Pull request merged**
